name: test2zfroma
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI + State
  cupertino_icons: ^1.0.8
  provider: ^6.1.1

  # Network + Backend
  http: ^1.4.0
  dio: ^5.8.0+1
  mqtt_client: ^10.0.0

  # Storage
  shared_preferences: ^2.2.2

  # Device Features
  google_maps_flutter: ^2.6.0
  image_picker: ^1.1.0
  flutter_reactive_ble: ^5.4.0
  permission_handler: ^11.3.0

  # Security
  encrypt: ^5.0.3

  # File Handling
  mime: ^2.0.0
  http_parser: ^4.1.2
  url_launcher: ^6.3.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  xml: ^6.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/map.jpg
    - assets/images/logo.jpg
    - assets/images/car3.jpg
    - assets/images/car2.png
    - assets/images/small.png
    - assets/images/car4.jpg
    - assets/images/dd.jpg
    - assets/images/logo_s.jpg
